### ISSUE TITLE
improve --tag and --service

### ISSUE THREAD

**Issue by zhuosun** [adjust/bagger#12]
There are quite often cases where we need to pull all related logs for a specific `app token + device ID`. In this cases, we would need to get all `tag` and in both `adjust_server` and `callback_worker`.

It would be convenient to have `--tag all` and `--service all`.

When set `--tag all`, it means `--tag impression,click,install,session,event,reattribution,update`
When set `--service all`, it means `--service adjust_server,callback_worker`. ( later on, we might want to add `attribution_worker`, too.)

**Comment by roa** [comment]
you already have that behaviour if you just omit `tag` and / or `service`

**Comment by zhuosun** [comment]
I tried once without tag and it gave me error. I will confirm this tomorrow.

**Comment by zhuosun** [comment]
tested but still not working.... ( talking in slack but reopen it here )
