### ISSUE TITLE
new logging tool updates

### ISSUE THREAD

**Issue by zhuosun** [adjust/bagger#3]
many thanks to @roa for the session and here are the points that we discussed:

### Indexed Fields 

- [x] To be removed:
"message->'host'"
"message->'context'->'request'->'Form'->'install_callback'"
"message->'context'->'request'->'Form'->'referrer'"
"message->'context'->'request'->'URL'"

- [x] To be added:
"message->'context'->'device_ids'->'win_adid'"
"message->'context'->'callback'->'Body'"
"message->'context'->'session'->'RejectedEngagement'->'Tracker'"
"message->'context'->'session'->'RejectedEngagement'->'RejectedInstallPingback'"
"message->'context'->'request'->'Form'->'source'"
"message->'context'->'sdk_click'->'tracker'"
"message->'context'->'request'->'Form'->'partner_params'"
"message->'context'->'request'->'Form'->'callback_params'"
"message->'context'->'sdk_click'->'deeplink'"
"message->'context'->'callback'->'Data'->'AppVersion'"
"message->'context'->'callback'->'Data'->'AppVersionShort'"
"message->'context'->'callback'->'Data'->'LastAppVersion'"
"message->'context'->'callback'->'Data'->'LastAppVersionShort'"
"message->'context'->'callback'->'Data'->'Environment'"
"message->'context'->'request'->'Form'->'environment'"

### Tool setup
- [x] add a top level partition for servers: `adjust_server` and `callback_worker`, and make it indexed to `"message->'service'"` field
- [x] add `-o output.log` functinon: for now not sorted. Check with AM
- [x] put the `host` and `job` into default script
- [x]  `or` logic for tag: `--tag 'sdk_click,click,install'`
- [ ] create short terms for each field, so you do not have to write "message->'bla'->'bla'" all the time
- [x] option to write the command line into the output file: `--cmd`
- [x] selectively output certain fields, beside the whole line. E.g. `--fields "message->'context'->'app_token', message->'device_ids'->'idfa'"` only outputs the `app token` and the `IDFA`. If `--fields` NOT defined, then output the whole `message`
- [x] add `--count` command to only output the number of lines

@adjust/integration to follow up

**Comment by zhuosun** [comment]
`option to write the command line into the output file: --cmd` means output the commands that you run to get the file. For example, I run:

```
pull.pl --cmd --filter "log->'context'->'callback'->'Label' ? 'google_connector' AND log->>'service' = 'callback_worker'" --from '2017_07_21_14:00' --until '2017_07_21_15:00' --tags sdk_click --out roa5
```
Then in file `roa5`, the first line a copy of above command

**Comment by zhuosun** [comment]
For the mapping, I am actually waiting for the new added fields, so that we can map them all at once.

**Comment by zhuosun** [comment]
all new indexes should/can be used as stand alone searches. But I don't see how this matters?

**Comment by roa** [comment]
new indexes are added starting from 2017_07_24_18

**Comment by roa** [comment]
except the mapping all is done

**Comment by zhuosun** [comment]
update the issue description to add `--count` option

**Comment by roa** [comment]
it's added and deployed. for future features it would be nice if we could open one issue / feature request.

**Comment by zhuosun** [comment]
most of the points are finished here. The only one left is the 
```
create short terms for each field, so you do not have to write "message->'bla'->'bla'" all the time
```
we will work on that in a separate issue.
